In [8]:
import pandas as pd

# Load dataset, treating 'NAN' aÂµnd similar as missing values
df = pd.read_csv("ibtracs.csv", na_values=["NAN", "nan", "NaN" , " " , None])

# Count missing values per column
missing_df = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage': (df.isnull().sum() / len(df)) * 100
}).sort_values(by='Percentage', ascending=False)

num_cols_high_missing = (df.isnull().sum() / len(df) > 0.5).sum()


print(f"Number of Columns with >50% Missing Values: {num_cols_high_missing}")
print(missing_df['Percentage']['TD9636_STAGE'])
# Display missing values summary
print(missing_df[missing_df['Percentage'] < 80])

<ipython-input-8-86e4e45d895c>:4: DtypeWarning: Columns (1,8,9,10,11,12,14,15,19,20,21,23,24,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,45,46,48,49,51,52,54,55,57,58,59,60,61,62,63,64,65,66,67,68,70,71,73,74,75,76,77,78,79,81,82,83,84,86,87,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,106,107,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,128,129,131,132,133,134,135,136,137,138,139,140,141,142,143,145,146,147,148,149,150,151,152,153,154,155,156,157,158,160,161,162,163,164,165,166,167,168,169,170,171,172,173) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("ibtracs.csv", na_values=["NAN", "nan", "NaN" , " " , None])

Number of Columns with >50% Missing Values: 151
83.72831951639016
               Missing Values  Percentage
USA_R34_SW             227284   76.501099
USA_R34_NW             227254   76.491001
USA_R34_SE             227240   76.486289
USA_R34_NE             227229   76.482587
CMA_WIND               223466   75.216005
CMA_LAT                223428   75.203215
CMA_PRES               223428   75.203215
CMA_LON                223428   75.203215
CMA_CAT                222600   74.924520
TOKYO_PRES             220931   74.362755
TOKYO_LAT              220931   74.362755
TOKYO_LON              220931   74.362755
TOKYO_R30_DIR          220678   74.277598
TOKYO_R50_DIR          220678   74.277598
TOKYO_GRADE            220677   74.277261
USA_RMW                191981   64.618528
USA_ROCI               191950   64.608094
USA_POCI               191522   64.464034
WMO_WIND               184425   62.075268
WMO_PRES               176033   59.250620
USA_AGENCY             169766   57.141222
WMO_AGENCY             166482   56.035867
USA_PRES               146629   49.353582
USA_STATUS             128611   43.288937
USA_WIND                45997   15.482045
USA_LON                 45024   15.154544
USA_LAT                 45024   15.154544
USA_ATCF_ID             43215   14.545656
BASIN                   40519   13.638215
SUBBASIN                32647   10.988593
LANDFALL                 4767    1.604516
STORM_SPEED                 8    0.002693
STORM_DIR                   8    0.002693
IFLAG                       1    0.000337
TRACK_TYPE                  1    0.000337
NATURE                      1    0.000337
ISO_TIME                    1    0.000337
NAME                        1    0.000337
NUMBER                      1    0.000337
SID                         1    0.000337
SEASON                      0    0.000000
USA_SSHS                    0    0.000000
DIST2LAND                   0    0.000000
LON                         0    0.000000
LAT                         0    0.000000

In [12]:
len(df)

297099

In [13]:
# prompt: can you create a dataframe where df['TD9636_STAGE'] is not null

import pandas as pd

# Load dataset, treating various representations of missing values
df = pd.read_csv("ibtracs.csv", na_values=["NAN", "nan", "NaN", " ", None])

# Create a new DataFrame where 'TD9636_STAGE' is not null
df_filtered = df[df['TD9636_STAGE'].notnull()]

# Display or use the filtered DataFrame
df_filtered['TD9636_STAGE']

<ipython-input-13-b2d9b934e1c5>:6: DtypeWarning: Columns (1,8,9,10,11,12,14,15,19,20,21,23,24,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,45,46,48,49,51,52,54,55,57,58,59,60,61,62,63,64,65,66,67,68,70,71,73,74,75,76,77,78,79,81,82,83,84,86,87,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,106,107,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,128,129,131,132,133,134,135,136,137,138,139,140,141,142,143,145,146,147,148,149,150,151,152,153,154,155,156,157,158,160,161,162,163,164,165,166,167,168,169,170,171,172,173) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("ibtracs.csv", na_values=["NAN", "nan", "NaN", " ", None])

1        1.0
2        1.0
3        1.0
4        1.0
5        1.0
        ...
67406    1.0
67407    1.0
67408    1.0
67409    1.0
67410    1.0
Name: TD9636_STAGE, Length: 48343, dtype: float64

In [10]:
df_filtered['TD9636_STAGE'].unique()

array([1., 2., 4., 0., 6., 5., 3.])

In [14]:
# prompt: df_filtered['TD9636_STAGE'] how many rows for each unique value

print(df_filtered['TD9636_STAGE'].value_counts())

TD9636_STAGE
2.0    17204
1.0    16028
4.0    10623
0.0     3156
3.0      742
5.0      331
6.0      259
Name: count, dtype: int64

In [18]:
missing_df = pd.DataFrame({
    'Missing Values': df_filtered.isnull().sum(),
    'Percentage': (df_filtered.isnull().sum() / len(df_filtered)) * 100
}).sort_values(by='Percentage', ascending=False)

In [19]:
missing_df

                Missing Values  Percentage
MLC_LAT                  48343       100.0
BOM_R50_NE               48343       100.0
REUNION_R50_NW           48343       100.0
REUNION_R64_NE           48343       100.0
REUNION_R64_SE           48343       100.0
...                        ...         ...
NAME                         0         0.0
SUBBASIN                     0         0.0
BASIN                        0         0.0
NUMBER                       0         0.0
SID                          0         0.0

[174 rows x 2 columns]

In [20]:
missing_df[missing_df['Percentage'] < 50].index

Index(['TD9636_WIND', 'USA_WIND', 'USA_LAT', 'USA_LON', 'USA_ATCF_ID',
       'TD9636_LAT', 'TD9636_LON', 'LANDFALL', 'STORM_SPEED', 'STORM_DIR',
       'TD9636_STAGE', 'SEASON', 'USA_SSHS', 'IFLAG', 'DIST2LAND',
       'TRACK_TYPE', 'LON', 'LAT', 'NATURE', 'ISO_TIME', 'NAME', 'SUBBASIN',
       'BASIN', 'NUMBER', 'SID'],
      dtype='object')

In [21]:
Final_ibtracs = df_filtered[['TD9636_WIND', 'USA_WIND', 'USA_LAT', 'USA_LON', 'USA_ATCF_ID',
       'TD9636_LAT', 'TD9636_LON', 'LANDFALL', 'STORM_SPEED', 'STORM_DIR',
       'TD9636_STAGE', 'SEASON', 'USA_SSHS', 'IFLAG', 'DIST2LAND',
       'TRACK_TYPE', 'LON', 'LAT', 'NATURE', 'ISO_TIME', 'NAME', 'SUBBASIN',
       'BASIN', 'NUMBER', 'SID']]

In [22]:
Final_ibtracs['STORM_DIR']#.unique()

1          350
2          350
3          360
4           10
5           20
         ...
67406    250.0
67407    250.0
67408    250.0
67409    250.0
67410    250.0
Name: STORM_DIR, Length: 48343, dtype: object

In [24]:
missing_df = pd.DataFrame({
    'Missing Values': Final_ibtracs.isnull().sum(),
    'Percentage': (Final_ibtracs.isnull().sum() / len(Final_ibtracs)) * 100
}).sort_values(by='Percentage', ascending=False)

In [25]:
missing_df

              Missing Values  Percentage
TD9636_WIND             8647   17.886767
USA_WIND                7876   16.291914
USA_LAT                 7083   14.651552
USA_LON                 7083   14.651552
USA_ATCF_ID             6652   13.760007
TD9636_LAT              1042    2.155431
TD9636_LON              1042    2.155431
LANDFALL                 450    0.930848
STORM_DIR                  1    0.002069
STORM_SPEED                1    0.002069
NUMBER                     0    0.000000
BASIN                      0    0.000000
LAT                        0    0.000000
SUBBASIN                   0    0.000000
NAME                       0    0.000000
ISO_TIME                   0    0.000000
NATURE                     0    0.000000
USA_SSHS                   0    0.000000
LON                        0    0.000000
TRACK_TYPE                 0    0.000000
DIST2LAND                  0    0.000000
IFLAG                      0    0.000000
SEASON                     0    0.000000
TD9636_STAGE               0    0.000000
SID                        0    0.000000

In [26]:

Final_ibtracs['USA_ATCF_ID'] = Final_ibtracs['USA_ATCF_ID'].fillna('')

<ipython-input-26-7be5d2ae882b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['USA_ATCF_ID'] = Final_ibtracs['USA_ATCF_ID'].fillna('')

In [27]:


Final_ibtracs['STORM_SPEED'] = pd.to_numeric(Final_ibtracs['STORM_SPEED'], errors='coerce')

mean_wind = Final_ibtracs['STORM_SPEED'].mean()

Final_ibtracs['STORM_SPEED'].fillna(mean_wind, inplace=True)



Final_ibtracs['STORM_DIR'] = pd.to_numeric(Final_ibtracs['STORM_DIR'], errors='coerce')

mean_wind = Final_ibtracs['STORM_DIR'].mean()

Final_ibtracs['STORM_DIR'].fillna(mean_wind, inplace=True)

<ipython-input-27-688a949d2fc6>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['STORM_SPEED'] = pd.to_numeric(Final_ibtracs['STORM_SPEED'], errors='coerce')
<ipython-input-27-688a949d2fc6>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_ibtracs['STORM_SPEED'].fillna(mean_wind, inplace=True)
<ipython-input-27-688a949d2fc6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['STORM_SPEED'].fillna(mean_wind, inplace=True)
<ipython-input-27-688a949d2fc6>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['STORM_DIR'] = pd.to_numeric(Final_ibtracs['STORM_DIR'], errors='coerce')
<ipython-input-27-688a949d2fc6>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_ibtracs['STORM_DIR'].fillna(mean_wind, inplace=True)
<ipython-input-27-688a949d2fc6>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['STORM_DIR'].fillna(mean_wind, inplace=True)

In [28]:
# fill Final_ibtracs['TD9636_WIND'] missing value with mean value

Final_ibtracs['TD9636_WIND'] = pd.to_numeric(Final_ibtracs['TD9636_WIND'], errors='coerce')

# Calculate the mean of 'TD9636_WIND', excluding NaN values
mean_wind = Final_ibtracs['TD9636_WIND'].mean()

# Fill NaN values in 'TD9636_WIND' with the calculated mean
Final_ibtracs['TD9636_WIND'].fillna(mean_wind, inplace=True)

<ipython-input-28-0b1c43cf22da>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['TD9636_WIND'] = pd.to_numeric(Final_ibtracs['TD9636_WIND'], errors='coerce')
<ipython-input-28-0b1c43cf22da>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_ibtracs['TD9636_WIND'].fillna(mean_wind, inplace=True)
<ipython-input-28-0b1c43cf22da>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['TD9636_WIND'].fillna(mean_wind, inplace=True)

In [29]:
Final_ibtracs['USA_WIND'] = pd.to_numeric(Final_ibtracs['USA_WIND'], errors='coerce')

# Calculate the mean of 'USA_WIND', excluding NaN values
mean_usa_wind = Final_ibtracs['USA_WIND'].mean()

# Fill NaN values in 'USA_WIND' with the calculated mean
Final_ibtracs['USA_WIND'].fillna(mean_usa_wind, inplace=True)

<ipython-input-29-6f6d906a84a2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['USA_WIND'] = pd.to_numeric(Final_ibtracs['USA_WIND'], errors='coerce')
<ipython-input-29-6f6d906a84a2>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_ibtracs['USA_WIND'].fillna(mean_usa_wind, inplace=True)
<ipython-input-29-6f6d906a84a2>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['USA_WIND'].fillna(mean_usa_wind, inplace=True)

In [30]:



Final_ibtracs['LANDFALL'] = pd.to_numeric(Final_ibtracs['LANDFALL'], errors='coerce')

# Calculate the mean of 'USA_WIND', excluding NaN values
mean_usa_wind = Final_ibtracs['LANDFALL'].mean()

# Fill NaN values in 'USA_WIND' with the calculated mean
Final_ibtracs['LANDFALL'].fillna(mean_usa_wind, inplace=True)

<ipython-input-30-5a6e6c7f6631>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['LANDFALL'] = pd.to_numeric(Final_ibtracs['LANDFALL'], errors='coerce')
<ipython-input-30-5a6e6c7f6631>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_ibtracs['LANDFALL'].fillna(mean_usa_wind, inplace=True)
<ipython-input-30-5a6e6c7f6631>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['LANDFALL'].fillna(mean_usa_wind, inplace=True)

In [31]:


Final_ibtracs['USA_LON'] = pd.to_numeric(Final_ibtracs['USA_LON'], errors='coerce')

# Calculate the mean of 'USA_WIND', excluding NaN values
mean_usa_wind = Final_ibtracs['USA_LON'].mean()

# Fill NaN values in 'USA_WIND' with the calculated mean
Final_ibtracs['USA_LON'].fillna(mean_usa_wind, inplace=True)

<ipython-input-31-d736f57573c0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['USA_LON'] = pd.to_numeric(Final_ibtracs['USA_LON'], errors='coerce')
<ipython-input-31-d736f57573c0>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_ibtracs['USA_LON'].fillna(mean_usa_wind, inplace=True)
<ipython-input-31-d736f57573c0>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['USA_LON'].fillna(mean_usa_wind, inplace=True)

In [32]:
Final_ibtracs['USA_LAT'] = pd.to_numeric(Final_ibtracs['USA_LAT'], errors='coerce')

# Calculate the mean of 'USA_WIND', excluding NaN values
mean_usa_wind = Final_ibtracs['USA_LAT'].mean()

# Fill NaN values in 'USA_WIND' with the calculated mean
Final_ibtracs['USA_LAT'].fillna(mean_usa_wind, inplace=True)

<ipython-input-32-063bb78b02b7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['USA_LAT'] = pd.to_numeric(Final_ibtracs['USA_LAT'], errors='coerce')
<ipython-input-32-063bb78b02b7>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_ibtracs['USA_LAT'].fillna(mean_usa_wind, inplace=True)
<ipython-input-32-063bb78b02b7>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['USA_LAT'].fillna(mean_usa_wind, inplace=True)

In [33]:

Final_ibtracs['TD9636_LAT'] = pd.to_numeric(Final_ibtracs['TD9636_LAT'], errors='coerce')

# Calculate the mean of 'USA_WIND', excluding NaN values
mean_usa_wind = Final_ibtracs['TD9636_LAT'].mean()

# Fill NaN values in 'USA_WIND' with the calculated mean
Final_ibtracs['TD9636_LAT'].fillna(mean_usa_wind, inplace=True)


# prompt: fill Final_ibtracs['USA_WIND'] missing value with mean value
Final_ibtracs['TD9636_LON'] = pd.to_numeric(Final_ibtracs['TD9636_LON'], errors='coerce')

# Calculate the mean of 'USA_WIND', excluding NaN values
mean_usa_wind = Final_ibtracs['TD9636_LON'].mean()

# Fill NaN values in 'USA_WIND' with the calculated mean
Final_ibtracs['TD9636_LON'].fillna(mean_usa_wind, inplace=True)

<ipython-input-33-8394e850297e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['TD9636_LAT'] = pd.to_numeric(Final_ibtracs['TD9636_LAT'], errors='coerce')
<ipython-input-33-8394e850297e>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_ibtracs['TD9636_LAT'].fillna(mean_usa_wind, inplace=True)
<ipython-input-33-8394e850297e>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['TD9636_LAT'].fillna(mean_usa_wind, inplace=True)
<ipython-input-33-8394e850297e>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['TD9636_LON'] = pd.to_numeric(Final_ibtracs['TD9636_LON'], errors='coerce')
<ipython-input-33-8394e850297e>:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_ibtracs['TD9636_LON'].fillna(mean_usa_wind, inplace=True)
<ipython-input-33-8394e850297e>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_ibtracs['TD9636_LON'].fillna(mean_usa_wind, inplace=True)

In [35]:
# prompt: export Final_ibtracs to csv

Final_ibtracs.to_csv('Final_ibtracs.csv', index=False)